name = "PackwizTest"
author = "Exo"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5947aca34f0d4a5eb5a2a4a4a4a3ba2c635b321ffaab81a8e8bde967c2b33ec5"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
